add select_any to CreateExternalMatchReq
Optable/match-api pull request #11
Opened 2022-06-17 18:47 UTC by juanli16

Add `select_any` field for `CreateExternalMatchReq` which will use all eligible/matchable ID types when set to true.

2022-06-17 18:52 UTC, xcapaldi approved these changes
LGTM

2022-06-17 18:59 UTC, amanjpro requested changes
wrong

2022-06-17 19:00 UTC, amanjpro approved these changes

2022-06-20 20:27 UTC, juanli16 commented
closing since we won't support this.

2022-06-20 20:27 UTC, closed without merging